# Generated by Django 4.1.1 on 2022-11-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=64)),
                ('groupeMed', models.CharField(max_length=64)),
                ('prix_de_vente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medicament')),
            ],
        ),
    ]
