# Generated by Django 4.1.1 on 2022-11-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupeMedicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicament',
            name='groupeMed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.groupemedicament'),
        ),
    ]
